version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DBNAME=${ORACLE_DATABASE}
      - DBUSERNAME=${ORACLE_USERNAME}
      - DBPASSWORD=${ORACLE_PASSWORD}
    depends_on:
      - db
  db:
    container_name: oracle
    image: container-registry.oracle.com/database/express
    ports:
      - ${ORALIST_HOST_PORT}:${ORALIST_CONTAINER_PORT}
      - 8080:8080
      - ${ORAEXP_HOST_PORT}:${ORAEXP_CONTAINER_PORT}
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PWD=${ORACLE_PASSWORD}
#     volumes:
#       - oracle:/opt/oracle/oradata
# volumes:
#   mydb:
