version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    container_name: oracle
    image: container-registry.oracle.com/database/express
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PWD=oracle
    volumes:
      - oracle:/opt/oracle/oradata
volumes:
  oracle:
