version: "3"
services:
  app:
    build: .
    ports:
      - ${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - DBNAME=${ORACLE_DATABASE}
      - DBUSERNAME=${ORACLE_USERNAME}
      - DBPASSWORD=${ORACLE_PASSWORD}
      - DBPORT=${ORALIST_HOST_PORT}
      - CONTAINER=${ORACLE_CONTAINER}
    depends_on:
      - db
  db:
    env_file: ./.env
    container_name: ${ORACLE_CONTAINER}
    image: container-registry.oracle.com/database/express
    restart: unless-stopped
    ports:
      - ${ORALIST_HOST_PORT}:${ORALIST_CONTAINER_PORT}
      - 8080:8080
      - ${ORAEXP_HOST_PORT}:${ORAEXP_CONTAINER_PORT}
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_PWD=${ORACLE_PASSWORD}
    volumes:
      - oracle:/opt/oracle/oradata
volumes:
  oracle:
